spring.application.name=website
spring.datasource.url=jdbc:postgresql://localhost:5432/eib-website
spring.datasource.username=postgres
spring.datasource.password=12345
spring.thymeleaf.cache=false
server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always