spring.application.name=website
spring.datasource.url=jdbc:postgresql://localhost:5432/eib-website
spring.datasource.username = postgres
spring.datasource.password = 221304
spring.thymeleaf.cache=false
server.port=8080
