--associations
INSERT INTO association (association_name) VALUES('DEMİR'),('DERİ'),('HUBUBAT'),('KONF'),('KURU MEYVE'),('MADEN'),('MOB. KAĞIT'),('SU ÜRÜN.'),('TEKSTİL'),('TÜTÜN'),('YAŞ MEYVE'),('ZEYTİN');
--categories
INSERT INTO category (category_name) VALUES('Aylık Sektörel Değerlendirme'),('Basın Duyurusu'),('DEİK İş Formu'),('Devlet Destekleri'),('Eğitim/Seminer'),('Fuar ve Heyet'),('Genel Duyuru'),('Görüş Talebi'),('İhale Duyurusu'),('İstatistik'),('Mevzuat'),('Sektörel Duyuru'),('Sınırda Karbon Düzenleme Mekanizması'),('Toplantı'),('Webinar'),('Yurtdışı Alım Talebi');

--announcements
INSERT INTO announcements (title, description, association_id, category_id,photo_url,more_info) VALUES ('Test Başlık','Demir için aylık sektörel duyuru falan filan',1,1,'https://images.pexels.com/photos/8428059/pexels-photo-8428059.jpeg?auto=compress&cs=tinysrgb&w=1400','www.google.com'),
('Deri Başlık','Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur',2,2,'https://images.pexels.com/photos/7698796/pexels-photo-7698796.jpeg','www.bing.com'),
('Hububat Başlık','Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa nisl malesuada lacinia integer nunc posuere. Ut hendrerit semper vel class aptent taciti sociosqu. ',3,3,'https://images.pexels.com/photos/9068367/pexels-photo-9068367.jpeg','www.youtube.com'),
('KONF Başlık','Lorem ipsum dolor sit amet consectetur adipiscing elit. Quisque faucibus ex sapien vitae pellentesque sem placerat. In id cursus mi pretium tellus duis convallis. Tempus leo eu aenean sed diam urna tempor. Pulvinar vivamus fringilla lacus nec metus bibendum egestas. Iaculis massa ',4,4,'https://images.pexels.com/photos/4175028/pexels-photo-4175028.jpeg','https://www.linuxfoundation.org/');